import { createSlice } from '@reduxjs/toolkit';

// Slice for filter
const filterSlice = createSlice({
  name: 'filter',
  initialState: '',
  reducers: {
    setFilter(state, action) {
      return action.payload;
    }
  }
});

// Export actions generated by createSlice
export const { setFilter } = filterSlice.actions;

// Export the reducer to be used in the store
export default filterSlice.reducer;



/*const SET_FILTER = 'SET_FILTER'

// Action creator
export const setFilter = (filter) => {
  return {
    type: SET_FILTER,
    payload: filter
  }
}

// Initial state for the filter
const initialState = ''

// Reducer for filter state
const filterReducer = (state = initialState, action) => {
  switch (action.type) {
    case SET_FILTER:
      return action.payload
    default:
      return state
  }
}

export default filterReducer*/